export default [
    {
        rank: 1,
        title: "STAY (with Justin Bieber)",
        singer: "The Kid LAROI",
        poster:
            "https://i.scdn.co/image/ab67616d0000b2738e6551a2944764bc8e33a960",
        state: "keep",
        id: 1,
        key: "kTJczUoc26U",
        like: 234867,
        done: false,
        album: "F*UCK LOVE3: OVER YOU",
    },
    {
        rank: 2,
        title: "INDUSTRY BABY (feat. Jack Harlow)",
        singer: "Lil Nas X",
        poster:
            "https://i.scdn.co/image/ab67616d0000b273ba26678947112dff3c3158bf",
        state: "up",
        id: 2,
        key: "UTHLKHL_whs",
        like: 61326,
        done: false,
        album: "INDUSTRY BABY(feat. Jack Harlow)",
    },
    {
        rank: 3,
        title: "Bad Habits",
        singer: "Ed Sheeran",
        poster:
            "https://i.scdn.co/image/ab67616d0000b273513d821e89b19367f6eb9e62",
        state: "up",
        id: 3,
        key: "orJSJGHjBLI",
        like: 87420,
        done: false,
        album: "Bad Habits",
    },
    {
        rank: 4,
        title: "Beggin'",
        singer: "Måneskin",
        poster:
            "https://i.scdn.co/image/ab67616d0000b273fa0ab3a28b5c52d8a5f97045",
        state: "up",
        id: 4,
        key: "zrFI2gJSuwA",
        like: 271545,
        done: false,
        album: "Chosen",
    },
    {
        rank: 5,
        title: "good 4 u",
        singer: "Olivia Rodrigo",
        poster:
            "https://charts-static.billboard.com/img/2021/06/olivia-rodrigo-3wl-sour-5yt-155x155.jpg",
        state: "keep",
        id: 5,
        key: "gNi_6U5Pm_o",
        like: 73823,
        done: false,
        album: "SOUR",
    },
    {
        rank: 6,
        title: "Need To Know",
        singer: "Doja Cat",
        poster:
            "https://charts-static.billboard.com/img/2021/07/doja-cat-1f3-planet-her-ja0-155x155.jpg",
        state: "up",
        id: 6,
        key: "dI3xkL7qUAc",
        like: 73356,
        done: false,
        album: "Planet Her",
    },
    {
        rank: 7,
        title: "Pepas",
        singer: "Farruko",
        poster:
            "https://i.scdn.co/image/ab67616d0000b273c77a01f0166fd8343d3a3edb",
        state: "up",
        id: 7,
        key: "y8trd3gjJt0",
        like: 133146,
        done: false,
        album: "Pepas",
    },
    {
        rank: 8,
        title: "Happier Than Ever",
        singer: "Billie Eilish",
        poster:
            "https://charts-static.billboard.com/img/2021/08/billie-eilish-lrt-happier-than-ever-rbn-155x155.jpg",
        state: "down",
        id: 8,
        key: "5GJWxDKyk3A",
        like: 112292,
        done: false,
        album: "Happier Than Ever",
    },
    {
        rank: 9,
        title: "Woman",
        singer: "Doja Cat",
        poster:
            "https://charts-static.billboard.com/img/2021/07/doja-cat-1f3-planet-her-ja0-155x155.jpg",
        state: "down",
        id: 9,
        key: "2V_uAAAH-_Q",
        like: 394328,
        done: false,
        album: "Planet Her",
    },
    {
        rank: 10,
        title: "Kiss Me More (feat. SZA)",
        singer: "Doja Cat",
        poster:
            "https://charts-static.billboard.com/img/2021/07/doja-cat-1f3-planet-her-ja0-155x155.jpg",
        state: "keep",
        id: 10,
        key: "0EVVKs6DQLo",
        like: 394328,
        done: false,
        album: "Planet Her",
    },
    {
        rank: 11,
        title: "MONTERO (Call Me By Your Name)",
        singer: "Lil Nas X",
        poster:
            "https://i.scdn.co/image/ab67616d0000b273664034dd80e91b28f773598d",
        state: "keep",
        id: 11,
        key: "6swmTBVI83k",
        like: 22925,
        done: false,
        album: "MONTERO (Call Me By Your Name)",
    },
    {
        rank: 12,
        title: "Todo De Ti",
        singer: "Rauw Alejandro",
        poster:
            "https://i.scdn.co/image/ab67616d0000b273c1449d5655128274517f3733",
        state: "keep",
        id: 12,
        key: "CFPLIaMpGrY",
        like: 143599,
        done: false,
        album: "VICE VERSA",
    },
    {
        rank: 13,
        title: "Take My Breath",
        singer: "The Weeknd",
        poster:
            "https://i.scdn.co/image/ab67616d0000b273e6c40bd47002f3faffb31ebe",
        state: "keep",
        id: 13,
        key: "rhTl_OyehF8",
        like: 131971,
        done: false,
        album: "TAKE MY BREATH",
    },
    {
        rank: 14,
        title: "Volví",
        singer: "Aventura",
        poster:
            "https://i.scdn.co/image/ab67616d0000b27312bcec4f18ee130369ce170c",
        state: "keep",
        id: 14,
        key: "ayd3yWr4tqU",
        like: 301700,
        done: false,
        album: "Volvi",
    },
    {
        rank: 15,
        title: "I WANNA BE YOUR SLAVE",
        singer: "Måneskin",
        poster:
            "https://i.scdn.co/image/ab67616d0000b2735aa05015cfa7bd2943c29b21",
        state: "up",
        id: 15,
        key: "yOb9Xaug35M",
        like: 57387,
        done: false,
        album: "Teatro Dira-Vol.1",
    },
    {
        rank: 16,
        title: "Yonaguni",
        singer: "Bad Bunny",
        poster:
            "https://i.scdn.co/image/ab67616d0000b27364afd6879102d03460bd3ad9",
        state: "up",
        id: 16,
        key: "doLMt10ytHY",
        like: 353721,
        done: false,
        album: "Yonaguni",
    },
];
